version: "3.9"
services:
db:
image: postgres:16
environment:
POSTGRES_PASSWORD: cvia
POSTGRES_DB: cvia
volumes: ["postgres_data:/var/lib/postgresql/data"]
restart: always


redis:
image: redis:7-alpine
restart: always


backend:
build: ./backend
env_file: .env
depends_on: [db, redis]
ports: ["8000:8000"]
command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


worker:
build: ./backend
env_file: .env
depends_on: [backend, redis]
command: celery -A celery_worker.celery worker --loglevel=info


frontend:
build: ./frontend
depends_on: [backend]
ports: ["3000:3000"]
command: npm run dev


volumes:
postgres_data: